//! Table générée à partir de `crates/collectors/src/proxmox/testdata/pve9` :
//! (point d'entrée encodé, réponse enregistrée).

pub(super) const FILES: &[(&str, &str)] = &[
    (
        "cluster-status",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/002-cluster-status.json"),
    ),
    (
        "cluster-resources",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/003-cluster-resources.json"),
    ),
    (
        "cluster-resources-type-vm",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/004-cluster-resources-type-vm.json"
        ),
    ),
    (
        "cluster-resources-type-storage",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/005-cluster-resources-type-storage.json"
        ),
    ),
    (
        "cluster-options",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/006-cluster-options.json"),
    ),
    (
        "cluster-ha-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/007-cluster-ha-status-current.json"
        ),
    ),
    (
        "cluster-ha-status-manager-status",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/008-cluster-ha-status-manager-status.json"
        ),
    ),
    (
        "cluster-ha-resources",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/009-cluster-ha-resources.json"
        ),
    ),
    (
        "cluster-backup",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/010-cluster-backup.json"),
    ),
    (
        "cluster-replication",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/011-cluster-replication.json"
        ),
    ),
    (
        "cluster-ceph-status",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/012-cluster-ceph-status.json"
        ),
    ),
    (
        "cluster-ceph-metadata",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/013-cluster-ceph-metadata.json"
        ),
    ),
    (
        "cluster-ceph-flags",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/014-cluster-ceph-flags.json"
        ),
    ),
    (
        "cluster-metrics-export",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/015-cluster-metrics-export.json"
        ),
    ),
    (
        "cluster-config-nodes",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/016-cluster-config-nodes.json"
        ),
    ),
    (
        "cluster-config-qdevice",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/017-cluster-config-qdevice.json"
        ),
    ),
    ("nodes", include_str!("../../../../collectors/src/proxmox/testdata/pve9/018-nodes.json")),
    (
        "nodes-node3-status",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/019-nodes-node3-status.json"
        ),
    ),
    (
        "nodes-node3-version",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/020-nodes-node3-version.json"
        ),
    ),
    (
        "nodes-node3-subscription",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/021-nodes-node3-subscription.json"
        ),
    ),
    (
        "nodes-node3-services",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/022-nodes-node3-services.json"
        ),
    ),
    (
        "nodes-node3-network",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/023-nodes-node3-network.json"
        ),
    ),
    (
        "nodes-node3-netstat",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/024-nodes-node3-netstat.json"
        ),
    ),
    (
        "nodes-node3-storage",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/025-nodes-node3-storage.json"
        ),
    ),
    (
        "nodes-node3-disks-list",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/026-nodes-node3-disks-list.json"
        ),
    ),
    (
        "nodes-node3-disks-zfs",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/027-nodes-node3-disks-zfs.json"
        ),
    ),
    (
        "nodes-node3-disks-lvm",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/028-nodes-node3-disks-lvm.json"
        ),
    ),
    (
        "nodes-node3-disks-lvmthin",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/029-nodes-node3-disks-lvmthin.json"
        ),
    ),
    (
        "nodes-node3-disks-directory",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/030-nodes-node3-disks-directory.json"
        ),
    ),
    (
        "nodes-node3-apt-update",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/031-nodes-node3-apt-update.json"
        ),
    ),
    (
        "nodes-node3-apt-versions",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/032-nodes-node3-apt-versions.json"
        ),
    ),
    (
        "nodes-node3-certificates-info",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/033-nodes-node3-certificates-info.json"
        ),
    ),
    (
        "nodes-node3-replication",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/034-nodes-node3-replication.json"
        ),
    ),
    (
        "nodes-node3-tasks-limit-50",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/035-nodes-node3-tasks-limit-50.json"
        ),
    ),
    (
        "nodes-node3-qemu",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/036-nodes-node3-qemu.json"),
    ),
    (
        "nodes-node3-lxc",
        include_str!("../../../../collectors/src/proxmox/testdata/pve9/037-nodes-node3-lxc.json"),
    ),
    (
        "nodes-node3-ceph-osd",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/038-nodes-node3-ceph-osd.json"
        ),
    ),
    (
        "nodes-node3-ceph-pool",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/039-nodes-node3-ceph-pool.json"
        ),
    ),
    (
        "nodes-node3-ceph-fs",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/040-nodes-node3-ceph-fs.json"
        ),
    ),
    (
        "nodes-node3-hardware-pci",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/041-nodes-node3-hardware-pci.json"
        ),
    ),
    (
        "nodes-node3-qemu-101-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/042-nodes-node3-qemu-101-status-current.json"
        ),
    ),
    (
        "nodes-node3-qemu-101-snapshot",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/043-nodes-node3-qemu-101-snapshot.json"
        ),
    ),
    (
        "nodes-node3-qemu-101-rrddata-timeframe-hour",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/044-nodes-node3-qemu-101-rrddata-timeframe-hour.json"
        ),
    ),
    (
        "nodes-node3-qemu-101-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/045-nodes-node3-qemu-101-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node3-qemu-101-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/046-nodes-node3-qemu-101-agent-network-get-interfaces.json"
        ),
    ),
    (
        "nodes-node3-qemu-105-rrddata-timeframe-hour",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/049-nodes-node3-qemu-105-rrddata-timeframe-hour.json"
        ),
    ),
    (
        "nodes-node3-qemu-105-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/050-nodes-node3-qemu-105-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node3-qemu-105-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/051-nodes-node3-qemu-105-agent-network-get-interfaces.json"
        ),
    ),
    (
        "nodes-node3-qemu-131-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/052-nodes-node3-qemu-131-status-current.json"
        ),
    ),
    (
        "nodes-node3-qemu-122-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/057-nodes-node3-qemu-122-status-current.json"
        ),
    ),
    (
        "nodes-node3-qemu-130-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/077-nodes-node3-qemu-130-status-current.json"
        ),
    ),
    (
        "nodes-node3-qemu-137-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/082-nodes-node3-qemu-137-status-current.json"
        ),
    ),
    (
        "nodes-node3-qemu-108-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/087-nodes-node3-qemu-108-status-current.json"
        ),
    ),
    (
        "nodes-node3-disks-smart-disk-2Fdev-2Fnvme0n1",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/090-nodes-node3-disks-smart-disk-2Fdev-2Fnvme0n1.json"
        ),
    ),
    (
        "nodes-node2-status",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/096-nodes-node2-status.json"
        ),
    ),
    (
        "nodes-node2-network",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/100-nodes-node2-network.json"
        ),
    ),
    (
        "nodes-node2-disks-list",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/103-nodes-node2-disks-list.json"
        ),
    ),
    (
        "nodes-node2-apt-update",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/108-nodes-node2-apt-update.json"
        ),
    ),
    (
        "nodes-node2-ceph-osd",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/115-nodes-node2-ceph-osd.json"
        ),
    ),
    (
        "nodes-node2-ceph-pool",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/116-nodes-node2-ceph-pool.json"
        ),
    ),
    (
        "nodes-node2-ceph-fs",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/117-nodes-node2-ceph-fs.json"
        ),
    ),
    (
        "nodes-node2-hardware-pci",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/118-nodes-node2-hardware-pci.json"
        ),
    ),
    (
        "nodes-node2-qemu-107-rrddata-timeframe-hour",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/126-nodes-node2-qemu-107-rrddata-timeframe-hour.json"
        ),
    ),
    (
        "nodes-node2-qemu-107-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/127-nodes-node2-qemu-107-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node2-qemu-107-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/128-nodes-node2-qemu-107-agent-network-get-interfaces.json"
        ),
    ),
    (
        "nodes-node2-qemu-103-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/137-nodes-node2-qemu-103-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node2-qemu-103-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/138-nodes-node2-qemu-103-agent-network-get-interfaces.json"
        ),
    ),
    (
        "nodes-node2-qemu-133-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/139-nodes-node2-qemu-133-status-current.json"
        ),
    ),
    (
        "nodes-node2-qemu-110-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/149-nodes-node2-qemu-110-status-current.json"
        ),
    ),
    (
        "nodes-node2-qemu-110-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/152-nodes-node2-qemu-110-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node2-qemu-110-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/153-nodes-node2-qemu-110-agent-network-get-interfaces.json"
        ),
    ),
    (
        "nodes-node2-disks-smart-disk-2Fdev-2Fsda",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/154-nodes-node2-disks-smart-disk-2Fdev-2Fsda.json"
        ),
    ),
    (
        "nodes-node1-network",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/164-nodes-node1-network.json"
        ),
    ),
    (
        "nodes-node1-apt-update",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/172-nodes-node1-apt-update.json"
        ),
    ),
    (
        "nodes-node1-ceph-osd",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/179-nodes-node1-ceph-osd.json"
        ),
    ),
    (
        "nodes-node1-ceph-pool",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/180-nodes-node1-ceph-pool.json"
        ),
    ),
    (
        "nodes-node1-ceph-fs",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/181-nodes-node1-ceph-fs.json"
        ),
    ),
    (
        "nodes-node1-qemu-100-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/203-nodes-node1-qemu-100-status-current.json"
        ),
    ),
    (
        "nodes-node1-qemu-128-status-current",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/238-nodes-node1-qemu-128-status-current.json"
        ),
    ),
    (
        "nodes-node1-qemu-128-agent-get-osinfo",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/241-nodes-node1-qemu-128-agent-get-osinfo.json"
        ),
    ),
    (
        "nodes-node1-qemu-128-agent-network-get-interfaces",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/242-nodes-node1-qemu-128-agent-network-get-interfaces.json"
        ),
    ),
    (
        "cluster-backup-backup-c98dc3da-6bed-included-volumes",
        include_str!(
            "../../../../collectors/src/proxmox/testdata/pve9/243-cluster-backup-backup-c98dc3da-6bed-included-volumes.json"
        ),
    ),
];
